ECommerce-App/ECommerce-App/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ECommerce_App.Models;
using ECommerce_App.Models.Interface;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce_App.Controllers
{
    public class ProductsController : Controller
    {
        public IFlummeryInventory _flummery { get; set; }

        /// <summary>
        /// Instantiates a new ProductsController object.
        /// </summary>
        /// <param name="flummery"></param>
        public ProductsController(IFlummeryInventory flummery)
        {
            _flummery = flummery;
        }

        /// <summary>
        /// Displays all the flummeries in a View.
        /// </summary>
        /// <returns>
        /// Task<IActionResult>: a list of all flummeries
        /// </returns>
        public async Task<IActionResult> Index()
        {
            List<Flummery> list = await _flummery.GetAllFlummeries();
            return View(list);
        }

        /// <summary>
        /// Displays all the flummeries sorted by the parameter string
        /// </summary>
        /// <param name="type">
        /// string: how to sort the flummeries
        /// </param>
        /// <returns>
        /// Task<IActionResult>: a list of all flummeries, sorted
        /// </returns>
        [HttpPost]
        public async Task<IActionResult> Index(string type)
        {
            List<Flummery> list = await _flummery.GetFlummeriesOrderedBy(type);
            return View(list);
        }

        /// <summary>
        /// Gets a subset of the flummeries from the parameter string
        /// </summary>
        /// <param name="search">
        /// string: the serach string used to match flummeries against
        /// </param>
        /// <returns>
        /// Task<IActionResult>: a subset of flummeries that match the search string
        /// </returns>
        public async Task<IActionResult> Details(string search)
        {
            List<Flummery> list = await _flummery.GetFlummeriesForSearch(search);
            return View(list);
        }
    }
}

ECommerce-App/ECommerce-App/ViewComponents/CartViewComponent.cs
using ECommerce_App.Data;
using ECommerce_App.Models;
using ECommerce_App.Models.Interface;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerce_App.ViewComponents
{
    [ViewComponent]
    public class CartViewComponent : ViewComponent
    {
        private ICart _cart;

        /// <summary>
        /// Instantiates a new CartViewComponent object.
        /// </summary>
        /// <param name="cart">
        /// ICart: an object that implements the ICart interface
        /// </param>
        public CartViewComponent(ICart cart)
        {
            _cart = cart;
        }

        /// <summary>
        /// Gets the current user's cart items.
        /// </summary>
        /// <param name="userId">
        /// string: the current user's ID
        /// </param>
        /// <returns>
        /// Task<IViewComponentResult>: a View containing the current user's cart items
        /// </returns>
        public async Task<IViewComponentResult> InvokeAsync(string userId)
        {
            var cart = await _cart.GetUserCart(userId);

            if(cart != null)
            {
                return View(cart.CartItems);
            }
            return View(new List<CartItem>());
        }
    }
}

ECommerce-App/ECommerce-App/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@using ECommerce_App.Models;
@inject SignInManager<ApplicationUser> SignInManager
<!DOCTYPE html>

<html>
<head>
    <title>Flummery Flummeries</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="shortcut icon" href="~/favicon/favicon.ico" />
    <link rel="apple-touch-icon" href="~/favicon/apple-touch-icon.png" />
    <link rel="icon" type="image/png" href="~/favicon/favicon-16x16.png" sizes="16x16" />
    <link rel="icon" type="image/png" href="~/favicon/favicon-32x32.png" sizes="32x32" />
    <link rel="stylesheet" type="text/css" href="~/Styles/reset.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="~/Styles/StyleSheet.css" />
    @RenderSection("Styles", false)
</head>

<body>
    <div class="all-container">
        <header>
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Products" class="nav-link">Products</a>
                        </li>
                    </ul>
                </div>
                <div class="mx-auto order-0">
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand mx-auto">
                        <img src="~/assets/puddingicon.png" class="flum-icon" />
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                    <ul class="navbar-nav ml-auto">
                        @if (SignInManager.IsSignedIn(User))
                        {
                        var currentUser = await SignInManager.UserManager.GetUserAsync(User);
                        <li class="cart-icon">
                            <div>
                                 @await Component.InvokeAsync("CartIcon", currentUser.Id)
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @User.Claims.First(x => x.Type == "FullName").Value
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                                @if (User.IsInRole("Admin"))
                                {
                                    <div class="dropdown-divider"></div>
                                    <form asp-page="/Admin/Index" method="get"> <button class="btn btn-link" type="submit">Admin Dash</button></form>
                                }
                            <form asp-page="/Orders/Orders" asp-route-page="1" method="post">
                                <button class="btn btn-link" type="submit">Orders</button>
                            </form>

                                <form asp-page="/Account/View" method="get"> <button class="btn btn-link" type="submit">Account</button></form>
                                <form asp-page="/Account/Logout" method="post"> <button class="btn btn-link" type="submit">Logout</button></form>
                            </div>
                        </li>
                        }
                        else
                        {
                        <li>
                            <a asp-page="/Account/Login" class="nav-link" role="button">Login</a>
                        </li>

                        <li>
                            <a asp-page="/Account/Register" class="nav-link" role="button">Register</a>
                        </li>
                        }
                    </ul>
                </div>
            </nav>
        </header>
        @if (SignInManager.IsSignedIn(User))
        {
            var currentUser = await SignInManager.UserManager.GetUserAsync(User);
            <div>
                @await Component.InvokeAsync("Cart", currentUser.Id)
            </div>
        }
        <div class="body-container">
            @RenderBody()
        </div>

        <footer>
            <div>Copyright FlummeryInc.</div>
            <div>Brought to you by</div>
            <div>Paul Rest and Nicco Ryan</div>
        </footer>
    </div>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js" integrity="sha384-XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J" crossorigin="anonymous"></script>
    <script src="~/Scripts/main.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>